/** @type {import('tailwindcss').Config} */
export default {
  important: '.stitch-workspace-root',
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#00575b',
        'on-error': '#450900',
        surface: '#0e0e0f',
        'primary-fixed': '#d0fb5a',
        'surface-container-low': '#131314',
        'outline-variant': '#484849',
        outline: '#767576',
        'on-secondary-fixed-variant': '#1341ca',
        'surface-container-highest': '#262627',
        'primary-container': '#88ae01',
        'surface-container-lowest': '#000000',
        'on-surface': '#ffffff',
        secondary: '#8097ff',
        primary: '#d3fe5d',
        'on-primary-container': '#1c2600',
        'tertiary-fixed-dim': '#00e5ee',
        'on-primary': '#4a6000',
        'on-primary-fixed': '#394b00',
        error: '#ff7351',
        'secondary-dim': '#4669f0',
        'on-secondary': '#00175f',
        'tertiary-dim': '#00e5ee',
        'error-dim': '#d53d18',
        'on-primary-fixed-variant': '#516900',
        'surface-dim': '#0e0e0f',
        'surface-container-high': '#201f21',
        'surface-bright': '#2c2c2d',
        'tertiary-fixed': '#00f4fe',
        'secondary-fixed': '#c7cfff',
        'on-tertiary-fixed-variant': '#006266',
        'secondary-container': '#043ac5',
        'primary-fixed-dim': '#c2ec4d',
        'on-background': '#ffffff',
        'inverse-on-surface': '#565556',
        'inverse-primary': '#4f6700',
        'surface-variant': '#262627',
        'on-tertiary-fixed': '#004346',
        'on-tertiary': '#006165',
        'tertiary-container': '#00f4fe',
        'surface-container': '#1a191b',
        'on-secondary-fixed': '#00278f',
        'on-surface-variant': '#adaaab',
        tertiary: '#a1faff',
        'primary-dim': '#c5ef50',
        background: '#0e0e0f',
        'inverse-surface': '#fcf8f9',
        'error-container': '#b92902',
        'surface-tint': '#d3fe5d',
        'secondary-fixed-dim': '#b4c1ff',
        'on-secondary-container': '#cfd6ff',
        'on-error-container': '#ffd2c8',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        label: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
    },
  },
  plugins: [],
}
